language : generic
sudo: required
services:
    - docker

before_install:
    - docker build -t krin325/docker-react -f Dockerfile.dev .

sctipt:
    - docker run -e CI=true krin325/docker-react npm run test